
project = "Nagendra Puthane"
author = "Nagendra Puthane"
copyright = "2026, Nagendra Puthane"

# -----------------------------------------------------------------------------
# GENERAL CONFIGURATION
# -----------------------------------------------------------------------------

# Sphinx extensions to enable additional features
extensions = []

# File patterns to ignore when looking for source files
exclude_patterns = []

# The suffix of source filenames (you write .rst files)
source_suffix = ".rst"

# The main/root document (without extension)
root_doc = "index"

# -----------------------------------------------------------------------------
# HTML OUTPUT CONFIGURATION
# -----------------------------------------------------------------------------

# The theme to use for HTML pages
html_theme = "furo"

# Theme-specific options
html_theme_options = {
    "light_css_variables": {
        "color-background-primary": "#FDFCFB",
        "color-background-secondary": "#F5F4F2",
        
        "color-foreground-primary": "#333333",
        "color-foreground-secondary": "#5C5C5C",
        
        "color-brand-primary": "#4A90A4",
        "color-brand-content": "#4A90A4",
    },
    
    # Dark mode colors
    "dark_css_variables": {
        "color-background-primary": "#1a1a1a",
        "color-background-secondary": "#242424",
        "color-foreground-primary": "#E0E0E0",
        "color-foreground-secondary": "#A0A0A0",
        "color-brand-primary": "#6BB8CC",
        "color-brand-content": "#6BB8CC",
    },
    
    # Navigation options
    "navigation_with_keys": True,  # Use arrow keys to navigate
}

# Title shown in browser tab
html_title = "Nagendra Puthane"

# Don't show "Created using Sphinx" in footer
html_show_sphinx = False

# Don't show copyright in footer
html_show_copyright = False

# Path to static files (CSS, images, etc.) - relative to this conf.py
# html_static_path = ["_static"]

# -----------------------------------------------------------------------------
# ADDITIONAL SETTINGS
# -----------------------------------------------------------------------------

# Language for content autogenerated by Sphinx
language = "en"

# Don't create a separate genindex page
html_use_index = False

# Don't add links to the source .rst files
html_show_sourcelink = False
